CREATE TABLE "ATG_3721_TIMESHEET"(
 "USER_ID" CHAR(8),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "BEG_WEEK" DATE,
 "SUN_HRS" FLOAT,
 "MON_HRS" FLOAT,
 "TUES_HRS" FLOAT,
 "WED_HRS" FLOAT,
 "THUR_HRS" FLOAT,
 "FRI_HRS" FLOAT,
 "SAT_HRS" FLOAT,
 "UPDATED" BIT NOT NULL);